#!/usr/bin/env python3
"""Turn results/summary.json into the handful of numbers worth quoting.

Everything published anywhere should come from here rather than from someone
reading a table and retyping it. Writes results/derived.json and docs/TABLES.md.
"""
import json
import os

from common import PAIRS, ROOT

S = json.load(open(f"{ROOT}/results/summary.json"))


def ep(mode, stack, endpoint, metric):
    try:
        return S[mode]["stacks"][stack]["endpoints"][endpoint][metric]
    except KeyError:
        return None


def stack(mode, name, key):
    try:
        return S[mode]["stacks"][name][key]
    except KeyError:
        return None


def r(v, n=1):
    return None if v is None else round(v, n)


def table(headers, rows, align=None):
    align = align or ["---"] * len(headers)
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join(align) + "|"]
    for row in rows:
        out.append("| " + " | ".join("-" if c is None else str(c) for c in row) + " |")
    return "\n".join(out) + "\n"


def n(v, d=0):
    return "-" if v is None else f"{v:,.{d}f}"


d = {"generated_from": "results/summary.json", "modes": {}}
md = ["# Tables", "",
      "Generated by `harness/derive.py`. Median of three runs.", ""]

# ---------- 1. the magic tax ----------
for mode in ("single", "tuned"):
    if mode not in S:
        continue
    rows, entry = [], {}
    for runtime, full, bare in PAIRS:
        t = S[mode]["magic_tax"].get(runtime)
        if not t:
            continue
        e = {
            "full": stack(mode, full, "label"), "bare": stack(mode, bare, "label"),
            "full_rps": r(ep(mode, full, "list", "rps")),
            "bare_rps": r(ep(mode, bare, "list", "rps")),
            "throughput_div": t.get("list_throughput_div"),
            "full_cpu_ms": ep(mode, full, "list", "cpu_ms_per_req"),
            "bare_cpu_ms": ep(mode, bare, "list", "cpu_ms_per_req"),
            "cpu_x": t.get("list_cpu_x"),
            "full_mem_mb": stack(mode, full, "mem_peak_mb"),
            "bare_mem_mb": stack(mode, bare, "mem_peak_mb"),
            "mem_x": t.get("mem_peak_x"),
            "boot_x": t.get("boot_x"),
        }
        entry[runtime] = e
        rows.append([runtime, f"{e['full']} ÷ {e['bare']}",
                     f"÷{e['throughput_div']}", f"×{e['cpu_x']}", f"×{e['mem_x']}", f"×{e['boot_x']}"])
    d["modes"].setdefault(mode, {})["magic_tax"] = entry
    md += [f"## Magic tax — `{mode}`", "",
           table(["runtime", "full ÷ bare", "throughput", "CPU per request", "memory", "boot"],
                 rows, ["---", "---", "--:", "--:", "--:", "--:"])]

# ---------- 2. absolute numbers ----------
for mode in ("single", "tuned"):
    if mode not in S:
        continue
    rows, entry = [], {}
    for name, s in S[mode]["stacks"].items():
        e = s["endpoints"].get("list")
        if not e:
            continue
        entry[name] = {"label": s["label"], "rps": r(e["rps"]), "cpu_ms": e["cpu_ms_per_req"],
                       "cores": e["cpu_used_cores"], "p50": e["p50_ms"], "p95": e["p95_ms"],
                       "p99": e["p99_ms"], "mem_peak_mb": s["mem_peak_mb"],
                       "mem_boot_mb": s["mem_boot_mb"], "boot_ms": s["boot_ms"],
                       "spread": e["rps_spread"]}
        rows.append([f"`{name}`", s["label"], n(e["rps"], 0),
                     f"±{e['rps_spread'] * 100:.1f}%" if e["rps_spread"] else "-",
                     n(e["cpu_ms_per_req"], 3), n(e["cpu_used_cores"], 2),
                     n(e["p50_ms"], 2), n(e["p99_ms"], 2),
                     n(s["mem_peak_mb"], 1), n(s["boot_ms"], 0)])
    d["modes"].setdefault(mode, {})["list"] = entry
    md += [f"## `GET /api/posts` — `{mode}`", "",
           table(["stack", "what it is", "rps", "spread", "CPU ms/req", "cores used",
                  "p50 ms", "p99 ms", "mem MB", "boot ms"], rows,
                 ["---", "---", "--:", "--:", "--:", "--:", "--:", "--:", "--:", "--:"])]

# ---------- 3. inside one Rails request ----------
layers, rows = {}, []
for mode in ("single",):
    for key, label in (("probe_static", "Rails, no database at all"),
                       ("probe_pluck", "same 4 queries, `pluck`, no AR objects"),
                       ("list", "same 4 queries, full Active Record")):
        e = S[mode]["stacks"]["rails"]["endpoints"].get(key)
        if not e:
            continue
        layers[key] = {"label": label, "rps": r(e["rps"]), "cpu_ms": e["cpu_ms_per_req"]}
    bare = S[mode]["stacks"]["rails-bare"]["endpoints"]["list"]
    layers["bare"] = {"label": "Rack + raw SQL (no Rails at all)", "rps": r(bare["rps"]),
                      "cpu_ms": bare["cpu_ms_per_req"]}
    order = ["probe_static", "bare", "probe_pluck", "list"]
    prev = None
    for k in order:
        if k not in layers:
            continue
        l = layers[k]
        step = f"÷{prev / l['rps']:.2f}" if prev else "-"
        rows.append([l["label"], n(l["rps"], 0), n(l["cpu_ms"], 3), step])
        prev = l["rps"]
d["rails_layers"] = layers
md += ["## Inside one Rails request — `single`", "",
       "Same middleware stack, same router, same renderer. Only the amount of",
       "Active Record changes. `Rack + raw SQL` is a different process and is",
       "shown for scale, not as a step in the same chain.", "",
       table(["what runs", "rps", "CPU ms/req", "vs the line above"], rows,
             ["---", "--:", "--:", "--:"])]

# ---------- 4. YJIT ----------
if "rails-noyjit" in S.get("single", {}).get("stacks", {}):
    rows = []
    y = {}
    for key, name in (("YJIT on (Rails 7.2+ default)", "rails"), ("YJIT off", "rails-noyjit")):
        e = ep("single", name, "list", "rps")
        c = ep("single", name, "list", "cpu_ms_per_req")
        m = stack("single", name, "mem_peak_mb")
        y[name] = {"rps": r(e), "cpu_ms": c, "mem_mb": m}
        rows.append([key, n(e, 0), n(c, 3), n(m, 1)])
    on, off = y["rails"], y["rails-noyjit"]
    y["throughput_gain"] = r(on["rps"] / off["rps"], 3) if off["rps"] else None
    y["cpu_saved"] = r(1 - on["cpu_ms"] / off["cpu_ms"], 3) if off["cpu_ms"] else None
    y["memory_cost_mb"] = r(on["mem_mb"] - off["mem_mb"], 1)
    d["yjit"] = y
    md += ["## YJIT — `single`", "",
           table(["", "rps", "CPU ms/req", "mem MB"], rows, ["---", "--:", "--:", "--:"]),
           "",
           f"YJIT is worth **×{y['throughput_gain']} throughput** on this workload "
           f"(**{y['cpu_saved'] * 100:.0f}% less CPU per request**) for "
           f"**+{y['memory_cost_mb']} MB**.", ""]

# ---------- 5. how much of the CPU was actually used ----------
rows, util = [], {}
for name, s in S.get("single", {}).get("stacks", {}).items():
    e = s["endpoints"].get("list")
    if not e or e.get("cpu_used_cores") is None:
        continue
    util[name] = {"cores": e["cpu_used_cores"], "mysql_cpu_ms": e.get("mysql_cpu_ms_per_req")}
    rows.append([f"`{name}`", n(e["cpu_used_cores"], 3),
                 f"{(1 - e['cpu_used_cores']) * 100:.0f}%", n(e.get("mysql_cpu_ms_per_req"), 3)])
d["cpu_utilisation_single"] = util
md += ["## How much of its one CPU each stack actually used — `single`", "",
       "One process, one thread, load concurrency 8. A number well under 1.0 means",
       "the stack spent that share of the window **waiting for MySQL**, not computing.", "",
       table(["stack", "cores used of 1.0", "idle waiting", "MySQL CPU ms/req"], rows,
             ["---", "--:", "--:", "--:"])]

# ---------- 6. worker memory / copy-on-write ----------
wpath = f"{ROOT}/results/workers.json"
if os.path.exists(wpath):
    w = json.load(open(wpath))
    rows = [[s["workers"], s["procs"], n(s["mem_peak_mb"], 1), n(s["naive_estimate_mb"], 1),
             f"×{s['overestimate_x']}", n(s["marginal_mb_per_worker"], 1), n(s["rps"], 0)]
            for s in w["samples"]]
    d["workers"] = w["samples"]
    md += ["## What an extra Puma worker really costs — Linux, `preload_app!`", "",
           table(["workers", "processes", "actual MB", "naive (workers × 1-worker)",
                  "overestimate", "marginal MB/worker", "rps"], rows,
                 ["--:", "--:", "--:", "--:", "--:", "--:", "--:"])]

with open(f"{ROOT}/results/derived.json", "w") as f:
    json.dump(d, f, indent=2)
with open(f"{ROOT}/docs/TABLES.md", "w") as f:
    f.write("\n".join(md))
print("\n".join(md))
