#!/usr/bin/env python3
"""Aggregate results/<mode>-run*.json into a median summary plus a markdown table.

    python3 harness/report.py            # writes results/summary.json, docs/RESULTS.md

Median of three runs, with the spread printed next to it. A spread wider than
±5% is flagged: at that point the number is not stable enough to argue from.
"""
import glob
import json
import os
import statistics as st

from common import PAIRS, ROOT, STACKS

METRICS = ["rps", "cpu_ms_per_req", "mysql_cpu_ms_per_req", "cpu_used_cores",
           "p50_ms", "p95_ms", "p99_ms", "mean_ms"]
ENDPOINTS = ["list", "detail", "create", "probe_static", "probe_pluck"]


def med(vals):
    vals = [v for v in vals if v is not None]
    return round(st.median(vals), 4) if vals else None


def spread(vals):
    """Half-width of the range as a fraction of the median."""
    vals = [v for v in vals if v is not None]
    if len(vals) < 2:
        return None
    m = st.median(vals)
    return round((max(vals) - min(vals)) / 2 / m, 4) if m else None


def load(mode):
    runs = []
    for path in sorted(glob.glob(f"{ROOT}/results/{mode}-run*.json")):
        with open(path) as f:
            runs.append(json.load(f))
    return runs


def summarise(mode):
    runs = load(mode)
    if not runs:
        return None
    out = {"mode": mode, "runs": len(runs), "concurrency": runs[0]["concurrency"],
           "versions": runs[0]["versions"], "stacks": {}, "warnings": []}
    names = list(runs[0]["stacks"])
    for name in names:
        entries = [r["stacks"][name] for r in runs if name in r["stacks"]]
        meta = entries[0]
        s = {"runtime": meta["runtime"], "variant": meta["variant"], "label": meta["label"],
             "env": meta["env"],
             "boot_ms": med([e["boot_ms"] for e in entries]),
             "mem_boot_mb": med([e["mem_boot"].get("working_set_mb") for e in entries]),
             "mem_boot_anon_mb": med([e["mem_boot"].get("anon_mb") for e in entries]),
             "mem_peak_mb": med([e["mem_peak_mb"] for e in entries]),
             "procs": meta["mem_boot"].get("procs"),
             "endpoints": {}}
        for ep in ENDPOINTS:
            vals = [e["endpoints"][ep] for e in entries if ep in e["endpoints"]]
            if not vals:
                continue
            d = {m: med([v.get(m) for v in vals]) for m in METRICS}
            d["rps_spread"] = spread([v["rps"] for v in vals])
            d["non_2xx"] = sum(v["non_2xx"] for v in vals)
            d["errors"] = sum(v["errors"] for v in vals)
            if d["rps_spread"] and d["rps_spread"] > 0.05:
                out["warnings"].append(
                    f"{name}/{ep}: rps spread ±{d['rps_spread'] * 100:.1f}% across {len(vals)} runs")
            if d["non_2xx"] or d["errors"]:
                out["warnings"].append(
                    f"{name}/{ep}: {d['non_2xx']} non-2xx, {d['errors']} errors")
            s["endpoints"][ep] = d
        out["stacks"][name] = s

    # the magic tax: full ÷ bare, inside one runtime
    out["magic_tax"] = {}
    for runtime, full, bare in PAIRS:
        if full not in out["stacks"] or bare not in out["stacks"]:
            continue
        f, b = out["stacks"][full], out["stacks"][bare]
        tax = {"full": full, "bare": bare,
               "mem_peak_x": round(f["mem_peak_mb"] / b["mem_peak_mb"], 2) if b["mem_peak_mb"] else None,
               "mem_boot_x": round(f["mem_boot_mb"] / b["mem_boot_mb"], 2) if b["mem_boot_mb"] else None,
               "boot_x": round(f["boot_ms"] / b["boot_ms"], 2) if b["boot_ms"] else None}
        for ep in ("list", "detail", "create"):
            if ep in f["endpoints"] and ep in b["endpoints"]:
                fe, be = f["endpoints"][ep], b["endpoints"][ep]
                tax[f"{ep}_throughput_div"] = round(be["rps"] / fe["rps"], 2) if fe["rps"] else None
                tax[f"{ep}_cpu_x"] = (round(fe["cpu_ms_per_req"] / be["cpu_ms_per_req"], 2)
                                      if be["cpu_ms_per_req"] else None)
        out["magic_tax"][runtime] = tax
    return out


def md_table(rows, headers, align=None):
    align = align or ["---"] * len(headers)
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join(align) + "|"]
    for r in rows:
        out.append("| " + " | ".join("" if c is None else str(c) for c in r) + " |")
    return "\n".join(out)


def fmt(v, n=1):
    return "-" if v is None else f"{v:,.{n}f}"


def main():
    summaries = {m: summarise(m) for m in ("single", "tuned")}
    summaries = {k: v for k, v in summaries.items() if v}
    os.makedirs(f"{ROOT}/docs", exist_ok=True)
    with open(f"{ROOT}/results/summary.json", "w") as f:
        json.dump(summaries, f, indent=2)

    doc = ["# Results", "",
           "Median of three runs. Generated by `harness/report.py` — do not edit by hand.", ""]
    any_s = next(iter(summaries.values()))
    v = any_s["versions"]
    doc += ["## Environment", "",
            "```",
            f"host          {v.get('host')}, {v.get('host_cpus')} CPUs visible to Docker",
            f"kernel        {v.get('kernel')} (containers)",
            f"docker        {v.get('docker')}",
            f"mysql         {v.get('mysql')}",
            f"ruby          {v.get('ruby')}",
            f"rails         {v.get('rails')} / puma {v.get('puma')} / mysql2 {v.get('mysql2_gem')}",
            f"node          {v.get('node')} / express {v.get('express')} / sequelize {v.get('sequelize')}",
            f"python        {v.get('python')} / django {v.get('django')} / gunicorn {v.get('gunicorn')}",
            f"go            {v.get('go_toolchain')} / gin {v.get('gin')} / gorm {v.get('gorm')}",
            "```", ""]

    for mode, s in summaries.items():
        doc += [f"## Mode `{mode}` — {s['stacks'][list(s['stacks'])[0]]['env']['APP_CPUS']} CPU, "
                f"concurrency {s['concurrency']}, {s['runs']} runs", ""]
        for ep, title in (("list", "`GET /api/posts` — 20 posts + authors + tags"),
                          ("detail", "`GET /api/posts/:id` — post + 20 comments + authors"),
                          ("create", "`POST /api/comments` — validate, insert, bump counter")):
            rows = []
            for name, d in s["stacks"].items():
                e = d["endpoints"].get(ep)
                if not e:
                    continue
                rows.append([f"**{name}**", d["label"], fmt(e["rps"]),
                             f"±{e['rps_spread'] * 100:.1f}%" if e["rps_spread"] else "-",
                             fmt(e["cpu_ms_per_req"], 3), fmt(e["cpu_used_cores"], 2),
                             fmt(e["p50_ms"], 2), fmt(e["p99_ms"], 2), fmt(d["mem_peak_mb"])])
            doc += [f"### {title}", "",
                    md_table(rows, ["stack", "what it is", "rps", "spread", "CPU ms/req",
                                    "cores used", "p50 ms", "p99 ms", "mem MB"],
                             ["---", "---", "--:", "--:", "--:", "--:", "--:", "--:", "--:"]), ""]

        rows = []
        for runtime, t in s["magic_tax"].items():
            rows.append([runtime, f"`{t['full']}` ÷ `{t['bare']}`",
                         f"÷{t['list_throughput_div']}" if t.get("list_throughput_div") else "-",
                         f"×{t['list_cpu_x']}" if t.get("list_cpu_x") else "-",
                         f"×{t['mem_peak_x']}" if t.get("mem_peak_x") else "-",
                         f"×{t['boot_x']}" if t.get("boot_x") else "-"])
        doc += [f"### The magic tax in `{mode}` — framework + ORM, everything else held equal", "",
                md_table(rows, ["runtime", "pair", "throughput", "CPU per request",
                                "memory", "boot time"],
                         ["---", "---", "--:", "--:", "--:", "--:"]), ""]

    warn = [w for s in summaries.values() for w in s["warnings"]]
    doc += ["## Warnings", ""]
    doc += ["```", *(warn or ["none"]), "```", ""]

    with open(f"{ROOT}/docs/RESULTS.md", "w") as f:
        f.write("\n".join(doc) + "\n")
    print("\n".join(doc))


if __name__ == "__main__":
    main()
