#!/usr/bin/env python3
"""Measure all eight stacks. One app container at a time, three endpoints each.

    python3 harness/run.py --runs 3 --mode single
    python3 harness/run.py --runs 3 --mode tuned

Writes results/<mode>-run<N>.json. Use harness/report.py to aggregate.

What gets recorded per endpoint: throughput, latency percentiles, the CPU the
app container actually burned during the window (from the cgroup, so it is CPU
seconds, not a sampled percentage), the CPU MySQL burned serving it, and
container memory before and after.
"""
import argparse
import json
import os
import time

from common import (ROOT, STACKS, compose, loadgen, mem_mb, mysql, sh, start, stop,
                    wait_db_idle)

MODES = {
    "single": dict(APP_CPUS="1.0", APP_MEM="1g", WEB_CONCURRENCY="1", APP_THREADS="1",
                   GOMAXPROCS="1", conc=8),
    "tuned":  dict(APP_CPUS="2.0", APP_MEM="1g", WEB_CONCURRENCY="2", APP_THREADS="5",
                   GOMAXPROCS="2", conc=50),
}

# Go and the bare Go app run one process; the others fork, and their pool is
# per process. The pool is sized to the load concurrency so that no stack is
# ever throttled by the connection pool rather than by its own CPU — an async
# runtime must be allowed to keep as many queries in flight as it can.
SINGLE_PROCESS = {"go", "go-bare"}

ENDPOINTS = [
    {"key": "list",   "path": "/api/posts?page=3",  "method": "GET"},
    {"key": "detail", "path": "/api/posts/4321",    "method": "GET"},
    # Unsaturated: with only 4 connections in flight nothing queues, so these
    # percentiles are service time rather than service time plus wait. It is the
    # only latency number in this repo worth quoting as "how long does a request
    # take"; every other one is measured at saturation on purpose.
    {"key": "list_idle", "path": "/api/posts?page=3", "method": "GET", "conc": 4,
     "modes": ["tuned"]},
    # Shorter window than the reads: at 10k rps a 10-second write test inserts
    # 150,000 rows, and cleaning those up leaves InnoDB purging into the next
    # stack's measurement.
    {"key": "create", "path": "/api/comments", "method": "POST", "duration": 6,
     "body": '{"post_id":1234,"user_id":7,"body":"comment %d generated by the load generator %d"}'},
]
RAILS_PROBES = [
    {"key": "probe_static", "path": "/api/static",           "method": "GET"},
    {"key": "probe_pluck",  "path": "/api/posts_pluck?page=3", "method": "GET"},
]

CREATE_POST_ID = 1234
COMMENT_HIGH_WATER = 40000


def cpu_usec(service):
    cid = compose(f"ps -q {service}").stdout.strip()
    if not cid:
        return None
    r = sh(f"docker exec {cid} sh -c 'cat /sys/fs/cgroup/cpu.stat 2>/dev/null | head -1'")
    try:
        return int(r.stdout.split()[1])
    except Exception:
        return None


def reload_db():
    """Rebuild the database from schema.sql + seed.sql before every run.

    The write test inserts and deletes hundreds of thousands of rows, which
    leaves the tables fragmented and the auto_increment far from where it
    started. Two runs against differently-aged tables are not the same
    experiment, and the effect is large: the round-trip-bound stacks moved
    by a third between two campaigns that differed only in database age.
    """
    t0 = time.time()
    r = sh("./db/load.sh")
    if r.returncode != 0:
        raise RuntimeError("db reload failed:\n" + r.stdout + r.stderr)
    print(f"  database reloaded from seed in {time.time() - t0:.0f}s", flush=True)


def reset_comments(baseline):
    mysql(f"DELETE FROM comments WHERE id > {COMMENT_HIGH_WATER}")
    mysql(f"UPDATE posts SET comments_count = {baseline} WHERE id = {CREATE_POST_ID}")


def _pkg_version(image, path):
    r = sh(f"docker run --rm --entrypoint cat {image} {path}")
    try:
        return json.loads(r.stdout)["version"]
    except Exception:
        return None


def _gomod(app, mod):
    try:
        for line in open(f"{ROOT}/apps/{app}/go.mod"):
            if mod in line:
                return line.strip().split()[-1]
    except OSError:
        pass
    return None


def versions():
    out = {}
    out["ruby"] = sh("docker run --rm --entrypoint ruby blogbench/rails -v").stdout.strip()
    r = sh("docker run --rm --entrypoint sh blogbench/rails -c "
           "'grep -A1 \"^    rails \" Gemfile.lock | head -1'")
    out["rails"] = sh("docker run --rm --entrypoint sh blogbench/rails -c "
                      "'bundle exec ruby -e \"require %q(rails/version); print Rails.version\"'"
                      ).stdout.strip() or r.stdout.strip()
    out["puma"] = _gem_version("blogbench/rails", "puma")
    out["mysql2_gem"] = _gem_version("blogbench/rails", "mysql2")
    out["node"] = sh("docker run --rm --entrypoint node blogbench/node -v").stdout.strip()
    out["express"] = _pkg_version("blogbench/node", "/app/node_modules/express/package.json")
    out["sequelize"] = _pkg_version("blogbench/node", "/app/node_modules/sequelize/package.json")
    out["mysql2_npm"] = _pkg_version("blogbench/node", "/app/node_modules/mysql2/package.json")
    out["python"] = sh("docker run --rm --entrypoint python blogbench/python -V").stdout.strip()
    out["django"] = sh("docker run --rm --entrypoint python blogbench/python -c "
                       "'import django; print(django.get_version())'").stdout.strip()
    out["gunicorn"] = sh("docker run --rm --entrypoint gunicorn blogbench/python --version").stdout.strip()
    out["go_toolchain"] = next(
        (l.split()[1] for l in open(f"{ROOT}/apps/go/Dockerfile") if l.startswith("FROM golang")),
        None)
    out["gin"] = _gomod("go", "gin-gonic/gin")
    out["gorm"] = _gomod("go", "gorm.io/gorm")
    out["go_sql_driver"] = _gomod("go-bare", "go-sql-driver/mysql")
    out["mysql"] = (mysql("SELECT VERSION()") or [["?"]])[0][0]
    cid = sh("docker compose ps -q mysql").stdout.strip()
    if cid:
        out["mysql_cpu_limit"] = sh(
            "docker inspect --format '{{.HostConfig.NanoCpus}}' " + cid).stdout.strip()
    out["docker"] = sh("docker version --format '{{.Server.Version}}'").stdout.strip()
    out["kernel"] = sh("docker run --rm --entrypoint uname blogbench/go-bare -sr").stdout.strip()
    out["host"] = sh("uname -sm").stdout.strip()
    out["host_cpus"] = sh("docker info --format '{{.NCPU}}'").stdout.strip()
    return {k: v for k, v in out.items() if v}


def _gem_version(image, gem):
    r = sh(f"docker run --rm --entrypoint sh {image} -c "
           f"\"grep -E '^    {gem} \\(' Gemfile.lock | head -1\"")
    t = r.stdout.strip()
    return t.split("(")[-1].rstrip(")") if "(" in t else None


def measure_stack(name, mode, conc, baseline_count):
    cfg = MODES[mode]
    procs = 1 if name in SINGLE_PROCESS else int(cfg["WEB_CONCURRENCY"])
    env = {k: v for k, v in cfg.items() if k.isupper()}
    env["DB_POOL"] = str(max(2, -(-cfg["conc"] // procs)))
    if name == "rails-noyjit":
        env["RAILS_YJIT"] = "0"
    service = "rails" if name == "rails-noyjit" else name

    entry = {"stack": name, "service": service, "mode": mode, "env": env,
             "runtime": STACKS[service]["runtime"], "variant": STACKS[service]["variant"],
             "label": STACKS[service]["label"], "endpoints": {}}

    boot_ms = start(service, env=env)
    try:
        entry["boot_ms"] = boot_ms
        time.sleep(1.5)
        entry["mem_boot"] = mem_mb(service)

        todo = [e for e in ENDPOINTS if mode in e.get("modes", [mode])]
        if name == "rails":
            todo += RAILS_PROBES

        peak = entry["mem_boot"].get("working_set_mb", 0)
        for ep in todo:
            # Warm up in a throwaway pass so the CPU counter below covers the
            # measurement window only. Reading it around a call that includes
            # its own warm-up would charge warm-up CPU to measured requests.
            c = ep.get("conc", conc)
            dur = ep.get("duration", 10)
            loadgen(service, ep["path"], c, 3, warmup=0,
                    method=ep["method"], body=ep.get("body"))
            c0, m0 = cpu_usec(service), cpu_usec("mysql")
            res = loadgen(service, ep["path"], c, dur, warmup=0,
                          method=ep["method"], body=ep.get("body"))
            c1, m1 = cpu_usec(service), cpu_usec("mysql")
            mem = mem_mb(service)
            if not ep["key"].startswith("probe_"):
                # the Rails-only probes run longer than the other stacks' sessions,
                # so they must not inflate the memory figure being compared
                peak = max(peak, mem.get("working_set_mb", 0))
            n = res["completed"] or 1
            res["cpu_ms_per_req"] = round((c1 - c0) / 1000.0 / n, 4) if c0 and c1 else None
            res["mysql_cpu_ms_per_req"] = round((m1 - m0) / 1000.0 / n, 4) if m0 and m1 else None
            if res["cpu_ms_per_req"]:
                # what fraction of the container's CPU allowance was actually used;
                # well under 1.0 per allotted core means the stack was waiting, not computing
                res["cpu_used_cores"] = round(res["rps"] * res["cpu_ms_per_req"] / 1000.0, 3)
                res["cpu_limit_cores"] = float(MODES[mode]["APP_CPUS"])
            # so a reader can confirm the database was never the constraint
            res["mysql_cores"] = (round((m1 - m0) / 1e6 / res["duration_s"], 2)
                                  if m0 and m1 else None)
            res["concurrency"] = c
            res["mem_after"] = mem
            entry["endpoints"][ep["key"]] = res
            print(f"    {ep['key']:<13} {res['rps']:>9.1f} rps  p50 {res['p50_ms']:>6.2f}ms  "
                  f"p99 {res['p99_ms']:>7.2f}ms  cpu {res['cpu_ms_per_req']}ms/req  "
                  f"({res.get('cpu_used_cores')}/{res.get('cpu_limit_cores')} cores, "
                  f"mysql {res.get('mysql_cores')})  "
                  f"mem {mem.get('working_set_mb')}MB  non2xx={res['non_2xx']} err={res['errors']}",
                  flush=True)
            if ep["key"] == "create":
                reset_comments(baseline_count)
                waited = wait_db_idle()
                print(f"      (waited {waited}s for InnoDB to settle)", flush=True)
        entry["mem_peak_mb"] = peak
    finally:
        stop(service)
    return entry


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--runs", type=int, default=3)
    ap.add_argument("--mode", choices=list(MODES) + ["both"], default="both")
    ap.add_argument("--only", default=None, help="comma-separated stack names")
    ap.add_argument("--no-reload", action="store_true",
                    help="skip the per-run database reload (faster, less comparable)")
    args = ap.parse_args()

    os.makedirs(f"{ROOT}/results", exist_ok=True)
    baseline = int(mysql(f"SELECT comments_count FROM posts WHERE id = {CREATE_POST_ID}")[0][0])
    reset_comments(baseline)

    modes = list(MODES) if args.mode == "both" else [args.mode]
    vers = versions()
    print(json.dumps(vers, indent=2))

    for mode in modes:
        names = list(STACKS)
        if mode == "single":
            names.insert(1, "rails-noyjit")   # only worth isolating without concurrency
        if args.only:
            wanted = set(args.only.split(","))
            names = [n for n in names if n in wanted]

        for run in range(1, args.runs + 1):
            print(f"\n{'=' * 70}\n  mode={mode}  run {run}/{args.runs}\n{'=' * 70}", flush=True)
            if not args.no_reload:
                reload_db()
                baseline = int(mysql(
                    f"SELECT comments_count FROM posts WHERE id = {CREATE_POST_ID}")[0][0])
            out = {"mode": mode, "run": run, "concurrency": MODES[mode]["conc"],
                   "versions": vers, "db_reloaded": not args.no_reload, "stacks": {}}
            for name in names:
                print(f"  [{name}]", flush=True)
                out["stacks"][name] = measure_stack(name, mode, MODES[mode]["conc"], baseline)
            path = f"{ROOT}/results/{mode}-run{run}.json"
            with open(path, "w") as f:
                json.dump(out, f, indent=2)
            print(f"  -> {path}", flush=True)

    reset_comments(baseline)


if __name__ == "__main__":
    main()
